import {
  AirVent,
  Armchair,
  Bath,
  BedDouble,
  BriefcaseMedical,
  CircleParking,
  Coffee,
  CookingPot,
  Droplet,
  Droplets,
  EvCharger,
  Fan,
  Flame,
  Heater,
  Microwave,
  Plug,
  Refrigerator,
  Shirt,
  ShowerHead,
  Toilet,
  Trash2,
  Utensils,
  UtensilsCrossed,
  WashingMachine,
  Wifi,
  Wind,
  Zap,
  type LucideIcon,
} from "lucide-react";
import type { AmenityId } from "@/content/types";

const icons: Record<AmenityId, LucideIcon> = {
  wifi: Wifi,
  parking: CircleParking,
  dishes: UtensilsCrossed,
  bedding: BedDouble,
  fireplace: Flame,
  wardrobe: Shirt,
  "coffee-machine": Coffee,
  "washing-machine": WashingMachine,
  refrigerator: Refrigerator,
  dishwasher: Utensils,
  "hair-dryer": Wind,
  iron: Shirt,
  grill: Flame,
  oven: Microwave,
  "outdoor-furniture": Armchair,
  "first-aid": BriefcaseMedical,
  toilet: Toilet,
  electricity: Zap,
  water: Droplet,
  shower: ShowerHead,
  trash: Trash2,
  ac: AirVent,
  "portable-fan": Fan,
  wastewater: Droplets,
  "black-water": Bath,
  "ev-charging": EvCharger,
  laundry: WashingMachine,
  "underfloor-heating": Heater,
  kitchenette: CookingPot,
};

export function AmenityIcon({ id, className = "size-5" }: { id: AmenityId; className?: string }) {
  const Icon = icons[id] ?? Plug;
  return <Icon className={className} strokeWidth={1.5} aria-hidden />;
}
