import type { Locale } from "./types";

/** Interface strings (buttons, labels, messages) in both languages. */
const en = {
  languageName: "English",
  languageShort: "ENG",
  menu: "Menu",
  languageSelection: "Language selection",
  close: "Close",
  home: "Homepage",
  bookNow: "Book now",
  learnMore: "Learn more",
  discover: "Discover",
  viewDetails: "View details",
  from: "from",
  perNight: "/ night",
  perPitchNight: "/ pitch / night",
  amenities: "Amenities",
  showAllAmenities: (n: number) => `Show all ${n} amenities`,
  showFewerAmenities: "Show fewer",
  reviews: "Reviews",
  alsoBookOn: "You can also book on",
  photos: "Photos",
  morePhotos: (n: number) => `+${n} photos`,
  previous: "Previous",
  next: "Next",
  // Booking
  dates: "Dates",
  checkIn: "Check-in",
  checkOut: "Check-out",
  guests: "Guests",
  adults: "Adults",
  adultsHint: "Age 13+",
  children: "Children",
  childrenHint: "Age 2–12",
  infants: "Babies",
  infantsHint: "Under 2",
  guestSummary: (a: number, c: number, i: number) =>
    [`${a} ${a === 1 ? "adult" : "adults"}`, c ? `${c} ${c === 1 ? "child" : "children"}` : "", i ? `${i} ${i === 1 ? "baby" : "babies"}` : ""]
      .filter(Boolean)
      .join(", "),
  checkAvailability: "Check availability",
  checking: "Checking…",
  nights: (n: number) => `${n} ${n === 1 ? "night" : "nights"}`,
  total: "Total",
  priceNote: "Final price is confirmed by our team. No payment is taken online.",
  errorDates: "Please choose a check-out date after the check-in date.",
  errorPast: "Please choose dates in the future.",
  errorGuests: "Please add at least one adult.",
  errorCapacity: (n: number) => `This accommodation sleeps up to ${n} guests.`,
  errorMinNights: (n: number) => `Minimum stay is ${n} nights.`,
  unavailable: "Unfortunately these dates are already booked. Please try other dates.",
  requestTitle: "Send a booking request",
  fullName: "Full name",
  email: "E-mail address",
  phoneOptional: "Phone number (optional)",
  message: "Message",
  messageOptional: "Message (optional)",
  sendRequest: "Send request",
  sending: "Sending…",
  requestSent: "Thank you! We have received your request and will reply to you by e-mail shortly.",
  somethingWrong: "Something went wrong. Please try again or contact us at info@oblun.com.",
  searchTitle: "Find your stay",
  searchHint: "Choose dates and guests to see prices and availability for every unit.",
  search: "Search",
  available: "Available",
  notAvailable: "Not available",
  tooManyGuests: "Too many guests",
  // Contact
  contactUs: "Contact us!",
  firstName: "Name",
  lastName: "Last name",
  agree: "I am familiar with and agree to the",
  termsLink: "Terms and conditions",
  and: "and",
  privacyLink: "Privacy policy",
  send: "Send",
  messageSent: "Thank you for your message! We will get back to you soon.",
  infoAndReservations: "Information and reservations",
  openInMaps: "Open in Google Maps",
  whatsapp: "WhatsApp",
  // Footer
  allRightsReserved: "All rights reserved.",
  notFoundTitle: "Page not found",
  notFoundText: "The page you are looking for doesn't exist or has been moved.",
  backHome: "Back to the homepage",
};

const me: typeof en = {
  languageName: "Crnogorski",
  languageShort: "MNE",
  menu: "Meni",
  languageSelection: "Izbor jezika",
  close: "Zatvori",
  home: "Naslovna",
  bookNow: "Rezerviši",
  learnMore: "Saznaj više",
  discover: "Otkrij",
  viewDetails: "Pogledaj detalje",
  from: "od",
  perNight: "/ noć",
  perPitchNight: "/ mjesto / noć",
  amenities: "Sadržaji",
  showAllAmenities: (n: number) => `Prikaži svih ${n} sadržaja`,
  showFewerAmenities: "Prikaži manje",
  reviews: "Utisci gostiju",
  alsoBookOn: "Možeš rezervisati i preko",
  photos: "Fotografije",
  morePhotos: (n: number) => `+${n} fotografija`,
  previous: "Prethodna",
  next: "Sljedeća",
  dates: "Datumi",
  checkIn: "Dolazak",
  checkOut: "Odlazak",
  guests: "Gosti",
  adults: "Odrasli",
  adultsHint: "13+ godina",
  children: "Djeca",
  childrenHint: "2–12 godina",
  infants: "Bebe",
  infantsHint: "Do 2 godine",
  guestSummary: (a: number, c: number, i: number) =>
    [
      `${a} ${a === 1 ? "odrasla osoba" : a < 5 ? "odrasle osobe" : "odraslih"}`,
      c ? `${c} ${c === 1 ? "dijete" : "djece"}` : "",
      i ? `${i} ${i === 1 ? "beba" : "bebe"}` : "",
    ]
      .filter(Boolean)
      .join(", "),
  checkAvailability: "Provjeri dostupnost",
  checking: "Provjera…",
  nights: (n: number) => `${n} ${n % 10 === 1 && n % 100 !== 11 ? "noć" : "noći"}`,
  total: "Ukupno",
  priceNote: "Konačnu cijenu potvrđuje naš tim. Plaćanje se ne vrši online.",
  errorDates: "Datum odlaska mora biti nakon datuma dolaska.",
  errorPast: "Izaberi datume u budućnosti.",
  errorGuests: "Dodaj bar jednu odraslu osobu.",
  errorCapacity: (n: number) => `Ovaj smještaj prima najviše ${n} gostiju.`,
  errorMinNights: (n: number) => `Minimalan boravak je ${n} noći.`,
  unavailable: "Nažalost, ovi datumi su već rezervisani. Pokušaj sa drugim datumima.",
  requestTitle: "Pošalji upit za rezervaciju",
  fullName: "Ime i prezime",
  email: "E-mail adresa",
  phoneOptional: "Broj telefona (opciono)",
  message: "Poruka",
  messageOptional: "Poruka (opciono)",
  sendRequest: "Pošalji upit",
  sending: "Slanje…",
  requestSent: "Hvala! Primili smo tvoj upit i uskoro ćemo ti odgovoriti putem e-maila.",
  somethingWrong: "Došlo je do greške. Pokušaj ponovo ili nam piši na info@oblun.com.",
  searchTitle: "Pronađi svoj smještaj",
  searchHint: "Izaberi datume i broj gostiju da vidiš cijene i dostupnost svih jedinica.",
  search: "Pretraži",
  available: "Dostupno",
  notAvailable: "Nije dostupno",
  tooManyGuests: "Previše gostiju",
  contactUs: "Kontaktirajte nas!",
  firstName: "Ime",
  lastName: "Prezime",
  agree: "Upoznat/a sam i saglasan/na sa",
  termsLink: "Uslovima korišćenja",
  and: "i",
  privacyLink: "Politikom privatnosti",
  send: "Pošalji",
  messageSent: "Hvala na poruci! Javićemo vam se uskoro.",
  infoAndReservations: "Info i rezervacije",
  openInMaps: "Otvori u Google mapama",
  whatsapp: "WhatsApp",
  allRightsReserved: "Sva prava zadržana.",
  notFoundTitle: "Stranica nije pronađena",
  notFoundText: "Stranica koju tražite ne postoji ili je premještena.",
  backHome: "Nazad na naslovnu",
};

const strings = { en, me };

export type UiStrings = typeof en;
export const ui = (lang: Locale): UiStrings => strings[lang];

export const htmlLang: Record<Locale, string> = { en: "en", me: "sr-Latn-ME" };
export const ogLocale: Record<Locale, string> = { en: "en_US", me: "sr_ME" };
